development: user=postgres password='admin' host=localhost port=5432 dbname=postgres sslmode=disable
test: user=youruser password='' host=localhost port=5432 dbname=bones_test sslmode=disable
production: user=youruser password='' host=localhost port=5432 dbname=bones_production sslmode=disable